### PR TITLE
[gcshop] new horn by Arstek

### PR DESCRIPTION
**Pull request by AleksCore**
Special for polish part of mr green community :) Kurwa.

### CODE REVIEW

**Comment by JarnoVgr** [comment]
Kurwa means ho right? Have mixed feelings about this.

**Comment by AleksCore** [comment]
no, it's more like "fuck". Too much meanings

**Comment by AleksCore** [comment]
this horn isn't offensive if you about this

**Comment by AleksCore** [comment]
Well, I also have mixed feeling about this horn. Sounds for horns should be in english and/or well-known. This one pretty weird and a bit annyoing. Close this pull request please

**Comment by AleksCore** [comment]
Oh, I can close it. Nice

**Pull request closed without merging**
