### PR TITLE
space seperator for gc text after you finish (You now have ... GC.)

### PR DESCRIPTION
**Pull request by Megas97**
added space seperator for gc text after you finish (You now have ... GC.)

### CODE REVIEW

**Comment by AleksCore** [comment]
It use comma as a separator, however we use space as separator in scoreboard, stats and in gc counter, so I guess we should use space separator everywhere, because it looks also good and not confusing.

**Comment by JarnoVgr** [comment]
Is it possible in MTA/Lua to have a separate utility functions that can be accessed from all resources? I think helper functions such as these should only be in the codebase once.

**Comment by AleksCore** [comment]
@JarnoVgr sure. 
<del>You need to define function as exported in meta.xml 
Here you can find correct syntax for it: https://wiki.multitheftauto.com/wiki/Meta.xml
And after this you can call your exported function using:</del>

https://wiki.multitheftauto.com/wiki/Call

**Comment by Megas97** [comment]
I removed the comma, making it use space. Just compared function in "gc" resource and what I did, looks same :D

**Comment by AleksCore** [comment]
Oh, true. My bad. Well, I'll merge it for now, later we'll probably do as Ywa suggested (as it's not really important)

**Comment by Megas97** [comment]
Yep, would be cool to just have it once, kinda like the Puma-Markers :) One zip but all maps can use it.

**Pull request merged**
