### PR TITLE
[race] missing audio files in meta.xml

### PR DESCRIPTION
**Pull request by AleksCore**
Weird, seems like somebody accidentally removed them, but it was before
GitHub.

### CODE REVIEW

**Comment by AleksCore** [comment]
I don't really understand why sometimes we hear this sounds, how is it even possible? No files in meta.xml means that they are not exist for scripts.

**Comment by JarnoVgr** [comment]
Can we rename the go!.mp3 sound? Having an exclamation mark in a filename feels wrong and may give problems in the future.

**Comment by EsDeKa** [comment]
@AleksCore If you have the file already downloaded (from before it was removed), playing the sound sometimes still works

**Comment by AleksCore** [comment]
@JarnoVgr yea, I agree. I'll rename it when I'll be at home or you can do it :)

**Comment by AleksCore** [comment]
Done.

**Pull request merged**
