### PR TITLE
16 new horns. 

### PR DESCRIPTION
**Pull request by d4marus**

### CODE REVIEW

**Comment by kolapp** [comment]
i have a feeling some of these gonna end up never bought.

**Comment by AleksCore** [comment]
Wew, that's an old PR

**Comment by AleksCore** [comment]
If anyone wants my opinion as a reviewer, I like 306; 311; 312; 314; 317; 318. (6 horns out of 16)

**Comment by AleksCore** [comment]
Merged https://github.com/JarnoVgr/Mr.Green-MTA-Resources/pull/362

**Pull request closed without merging**
