### PR TITLE
HORNS FINALLY

### PR DESCRIPTION
**Pull request by Flipper123**
HORNS FINALLY NEW HORNS :) @AleksCore @EsDeKa

### CODE REVIEW

**Comment by AleksCore** [comment]
Can you remake PR without this "Merge remote-tracking" commits?

**Comment by Flipper123** [comment]
idk why PR is with this 2 commits

**Comment by AleksCore** [comment]
https://mrgreengaming.com/forums/topic/17140-development-topic-lua-github-ask-here-if-you-need-help-with-git-or-the-resources/#comment-141288

Well, I can't accept this PR. This tutorial should help I hope. At least it used to work for me. Ask in this topic if  you have a problems

**Comment by AleksCore** [comment]
Well, seems like I need to fix the tutorial. Will do this asap

**Comment by AleksCore** [comment]
https://guides.github.com/activities/contributing-to-open-source/ Pull Request Pro Tips

**Comment by EsDeKa** [comment]
fucking git

**Comment by EsDeKa** [comment]
@JarnoVgr will merge it manually

**Comment by AleksCore** [comment]
Why git is so complex *scared and confused face*

**Comment by AleksCore** [comment]
@JarnoVgr, @EsDeKa nvm about this PR. 4f95d341c23b12aa19839832348b87b9aad585ba

**Pull request closed without merging**
